/** @type {import('ts-jest').JestConfigWithTsJest} */
module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  roots: ['<rootDir>/tests'],
  testMatch: ['**/*.test.ts'],
  moduleFileExtensions: ['ts', 'js', 'json'],
  collectCoverageFrom: [
    'src/**/*.ts',
    '!src/index.ts',
    '!src/test*.ts',
    '!src/comprehensive-test.ts',
    // Exclude DPMA integration code (requires live DPMA server)
    '!src/client/DPMAClient.ts',
    '!src/client/steps/BaseStep.ts',
    '!src/client/steps/Step1Applicant.ts',
    '!src/client/steps/Step2Lawyer.ts',
    '!src/client/steps/Step3DeliveryAddress.ts',
    '!src/client/steps/Step4Trademark.ts',
    '!src/client/steps/Step5NiceClasses.ts',
    '!src/client/steps/Step6Options.ts',
    '!src/client/steps/Step7Payment.ts',
    '!src/client/steps/Step8Final.ts',
    '!src/client/services/DocumentService.ts',
    '!src/client/services/VersandService.ts',
    '!src/client/http/HttpClient.ts',
  ],
  coverageDirectory: 'coverage',
  coverageReporters: ['text', 'lcov'],
  verbose: true,
  testTimeout: 10000,
};
